title: Pieter-Jan Inghelbrecht
description: >
  Research notes on systematic strategies, machine learning, and portfolio construction.

theme: minima

sass:
  style: compressed
  load_paths:
    - assets/css

classes: wide


plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

header_links:
  - label: Library
    url: /quants/2025/04/20/reading-and-tools.html

minima:
  skin: classic

# Add MathJax support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
